//columns mapping
const allAgentOnboardedColumns = [
    "AGENTCODE", "FIRST_NAME", "LAST_NAME", "DEVICE_SERIAL_NO", "STATUS", "CREATED_ON",
    "ADDRESS", "PHONE_NUMBER", "GENDER", "DOB", "PINCODE", "AADHAARNUMBER",
    "SETTLEMENT_ACC_NUM", "PERSONAL_ACC_NUM", "COMMUNICATION_ADDRESS", "PAN_NUMBER",
    "POSTOFFICE_ADDRESS", "LONGITUDE", "LATITUDE", "STATE", "DISTRICT", "SUBDISTRICT",
    "VILLAGENAME", "ZONALNAME", "ZONALCODE", "BRANCHNAME", "BRANCHCODE", "VENDORNAME",
    "VENDORCODE"
];

const agentOnboardedColumns = [
    "AGENTCODE", "FIRST_NAME", "LAST_NAME", "DEVICE_SERIAL_NO", "STATUS", "CREATED_ON",
    "ADDRESS", "PHONE_NUMBER", "GENDER", "DOB", "PINCODE", "AADHAARNUMBER",
    "SETTLEMENT_ACC_NUM", "PERSONAL_ACC_NUM", "COMMUNICATION_ADDRESS", "PAN_NUMBER",
    "POSTOFFICE_ADDRESS", "LONGITUDE", "LATITUDE", "STATE", "DISTRICT", "SUBDISTRICT",
    "VILLAGENAME", "ZONALNAME", "ZONALCODE", "BRANCHNAME", "BRANCHCODE", "VENDORNAME",
    "VENDORCODE"
];


const allAepsColumns = [
    "AGENT_CODE",
    "STATE_NAME",
    "STATE_CODE",
    "DISTRICT_NAME",
    "AGENTNAME",
    "BRANCHNAME",
    "CONTACT_NUMBER",
    "ADDRESS",
    "DEVICE_SERIAL_NO",
    "ON_US_TRANSACTION_COUNT",
    "OFFUS_TRANSACTION_COUNT",
    "ONUS_AMOUNT",
    "OFFUS_AMOUNT",
    "FINANCIAL_TXN_COUNT",
    "TPD_TXN_COUNT",
    "TPD_AMOUNT",
    "ONBOARDED_DATE",
    "STATUS",
    "FIRST_LOGIN_DAY",
    "LAST_TRANSACTION",
    "NO_OF_LOGIN_DAYS",
    "PMSBY_SUCCESS",
    "PMSBY_FAILURE",
    "PMJJBY_SUCCESS",
    "PMJJBY_FAILURE",
    "SBGEN_SUCCESS",
    "PMJDY_SUCCESS"
];

const vendorList=[
"ATYATI",
"ROINET",
"FIA",
"VISION INDIA",
"FINO",
"INTEGRA"
]

module.exports={allAgentOnboardedColumns,agentOnboardedColumns,allAepsColumns,vendorList}